export { default as Navbar }         from './Navbar/Navbar.jsx'
export { default as Footer }         from './Footer/Footer.jsx'
export { default as Button }         from './Button/Button.jsx'
export { default as Loader }         from './Loader/Loader.jsx'
export { default as Modal }          from './Modal/Modal.jsx'
export { default as SectionHeading } from './SectionHeading/SectionHeading.jsx'
